export { default as Tag } from './Tag.component'
export { default as Button } from './Button.component'
export { default as Input } from './Input.component'
export { default as Modal } from './Modal.component'
export { default as Card } from './Card.component'
export { default as Image } from './Image.component'
