export enum PokemonTypes {
  NORMAL = '노말',
  FIRE = '불',
  WATER = '물',
  GRASS = '풀',
  ELECTRIC = '전기',
  ICE = '얼음',
  FIGHTING = '격투',
  POISON = '독',
  GROUND = '땅',
  FLYING = '비행',
  PSYCHIC = '에스퍼',
  BUG = '벌레',
  ROCK = '바위',
  GHOST = '고스트',
  DRAGON = '드래곤',
  DARK = '악',
  STEEL = '강철',
  FAIRY = '페어리',
}

export enum TypesColor {
  NORMAL = '#A8A878',
  FIRE = '#F08030',
  WATER = '#6890F0',
  GRASS = '#78C850',
  ELECTRIC = '#F8D030',
  ICE = '#98D8D8',
  FIGHTING = '#C03028',
  POISON = '#A040A0',
  GROUND = '#E0C068',
  FLYING = '#A890F0',
  PSYCHIC = '#F85888',
  BUG = '#A8B820',
  ROCK = '#B8A038',
  GHOST = '#705898',
  DRAGON = '#7038F8',
  DARK = '#705848',
  STEEL = '#B8B8D0',
  FAIRY = '#EE99AC',
}

export enum TypeCompatibility {
  STRONG = 1,
  WEAK = -1,
  ZERO = 0,
}

export enum IconColor {
  NORMAL = '#f5f5d3',
  FIRE = '#ffc59b',
  WATER = '#bbcffe',
  GRASS = '#ddffcd',
  ELECTRIC = '#fff4ca',
  ICE = '#ddfafa',
  FIGHTING = '#ffaca7',
  POISON = '#ffb2ff',
  GROUND = '#fdf0cf',
  FLYING = '#e2d8ff',
  PSYCHIC = '#ffc1d4',
  BUG = '#f8ffbb',
  ROCK = '#fff0b0',
  GHOST = '#dcc7ff',
  DRAGON = '#ba9dff',
  DARK = '#f3d3be',
  STEEL = '#f3f3ff',
  FAIRY = '#ffd7e0',
}

export enum IconTypes {
  NORMAL = 'normal',
  FIRE = 'fire',
  WATER = 'water',
  GRASS = 'grass',
  ELECTRIC = 'electric',
  ICE = 'ice',
  FIGHTING = 'fighting',
  POISON = 'poison',
  GROUND = 'ground',
  FLYING = 'flying',
  PSYCHIC = 'psychic',
  BUG = 'bug',
  ROCK = 'rock',
  GHOST = 'ghost',
  DRAGON = 'dragon',
  DARK = 'dark',
  STEEL = 'steel',
  FAIRY = 'fairy',
}
